dist: xenial
language: python
python:
  - "3.7"
  - "3.8"

matrix:
  fast_finish: true

  include:
    # run pre-commit hooks checks
    - python: "3.8"
      before_install: pyenv global 3.8.0
      name: "Precommit all-files"
      env: TOXENV=lint

before_install:
  - pip install --upgrade pip
  - pip install codecov

install:
  - pip install tox

script:
  - tox
